# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b7b4ea3267ebec5909a0490bab72cc415f230b949dca62ebf2e6fc8251f2348f7f70018d4d35d1c1ba534f86a1cdabc6c875bc91a936e5fdfe3ad47897b87d4

test:
  secret_key_base: 1fc4d3557a9810c5ae4b1f1e2cd0c108ff4dee646f902bc2ec008762f4d7c1b03c66e1e20712bbd3c8f6ecc701e6176fc5c18ddfd1a75b7eed03b0461ba95f99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
